[package]
name = "git_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

[[bin]]
  name = "git-manager"
  path = "./src/main.rs"
